-- =============================================================================
-- SIGEA-GTT: Sistema Inteligente de Gestão de Eventos Adversos – Global Trigger Tool
-- Script DDL Consolidado (PostgreSQL 16+)
-- Arquivo: database/schemas/01_schema_completo.sql
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. TIPOS ENUMERADOS (ENUMS IDEMPOTENTES)
-- -----------------------------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'perfil_usuario_enum') THEN
        CREATE TYPE perfil_usuario_enum AS ENUM (
            'ADMINISTRADOR',
            'PROFESSOR',
            'ALUNO'
        );
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gravidade_ncc_merp_enum') THEN
        CREATE TYPE gravidade_ncc_merp_enum AS ENUM (
            'CATEGORIA_E', -- Dano temporário com necessidade de intervenção
            'CATEGORIA_F', -- Dano temporário com prolongamento de hospitalização
            'CATEGORIA_G', -- Dano permanente
            'CATEGORIA_H', -- Intervenção para suporte de vida (< 1h)
            'CATEGORIA_I'  -- Óbito com cuidado contribuinte
        );
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'status_submissao_enum') THEN
        CREATE TYPE status_submissao_enum AS ENUM (
            'EM_ANDAMENTO', -- Rascunho iniciado pelo aluno
            'SUBMETIDA',    -- Entregue pelo aluno, aguardando correção docente
            'AVALIADA'      -- Homologada com nota e parecer do professor
        );
    END IF;
END $$;

-- -----------------------------------------------------------------------------
-- 2. GESTÃO DE ACESSO E AUTENTICAÇÃO
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_completo VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    matricula_sigaa VARCHAR(12) UNIQUE,
    perfil perfil_usuario_enum NOT NULL,
    senha VARCHAR(255) NOT NULL,
    primeiro_acesso BOOLEAN NOT NULL DEFAULT TRUE,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- -----------------------------------------------------------------------------
-- 3. CONFIGURAÇÕES HOSPITALARES E METODOLOGIA IHI-GTT (45 GATILHOS / 5 MÓDULOS)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS unidades_hospitalares (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    sigla VARCHAR(20) NOT NULL,
    ativa BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS modulos_gtt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(30) UNIQUE NOT NULL,
    nome VARCHAR(100) NOT NULL,
    descricao TEXT,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS gatilhos_gtt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(10) NOT NULL UNIQUE,
    modulo_id BIGINT NOT NULL REFERENCES modulos_gtt(id) ON DELETE CASCADE,
    descricao TEXT NOT NULL,
    limiar_referencia VARCHAR(150),
    ativo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS categorias_eventos_adversos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE,
    definicao_operacional TEXT NOT NULL,
    ativa BOOLEAN NOT NULL DEFAULT TRUE
);

-- -----------------------------------------------------------------------------
-- 4. TURMAS ACADÊMICAS E MATRÍCULAS
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS turmas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    professor_responsavel_id BIGINT NOT NULL REFERENCES usuarios(id),
    codigo_disciplina VARCHAR(30) NOT NULL,
    nome_disciplina VARCHAR(150) NOT NULL DEFAULT 'Segurança do Paciente e Auditoria Clínica',
    periodo_letivo VARCHAR(20) NOT NULL,
    ano_semestre VARCHAR(10) NOT NULL,
    ativa BOOLEAN NOT NULL DEFAULT TRUE,
    criada_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS turma_alunos (
    turma_id BIGINT NOT NULL REFERENCES turmas(id) ON DELETE CASCADE,
    aluno_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    matriculado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (turma_id, aluno_id)
);

-- -----------------------------------------------------------------------------
-- 5. CASOS CLÍNICOS SIMULADOS (UNIFICAÇÃO DE CENÁRIO + PRONTUÁRIO DO PACIENTE)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS casos_clinicos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    professor_criador_id BIGINT NOT NULL REFERENCES usuarios(id),
    unidade_hospitalar_id BIGINT NOT NULL REFERENCES unidades_hospitalares(id),
    titulo VARCHAR(200) NOT NULL,
    descricao_caso TEXT NOT NULL,
    objetivos_aprendizagem TEXT NOT NULL,
    numero_atendimento VARCHAR(50) NOT NULL,
    idade_paciente INTEGER NOT NULL,
    data_admissao DATE NOT NULL,
    data_alta DATE NOT NULL,
    tempo_permanencia_dias INTEGER NOT NULL,
    sumario_alta TEXT NOT NULL,
    prescricoes_medicas TEXT NOT NULL,
    exames_laboratoriais TEXT NOT NULL,
    relatorio_cirurgico TEXT,
    evolucoes_multiprofissionais TEXT NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- -----------------------------------------------------------------------------
-- 6. ATIVIDADES PEDAGÓGICAS
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS atividades_educacionais (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    turma_id BIGINT NOT NULL REFERENCES turmas(id) ON DELETE CASCADE,
    caso_clinico_id BIGINT NOT NULL REFERENCES casos_clinicos(id) ON DELETE CASCADE,
    titulo VARCHAR(200) NOT NULL,
    orientacoes_pedagogicas TEXT,
    data_inicio TIMESTAMPTZ NOT NULL,
    data_fim TIMESTAMPTZ NOT NULL,
    tempo_limite_minutos INTEGER NOT NULL DEFAULT 20, -- Regra dos 20 min do IHI GTT
    ativa BOOLEAN NOT NULL DEFAULT TRUE,
    criada_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- -----------------------------------------------------------------------------
-- 7. SUBMISSÕES DOS DISCENTES E AVALIAÇÃO DOCENTE
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS submissoes_atividades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    atividade_id BIGINT NOT NULL REFERENCES atividades_educacionais(id) ON DELETE CASCADE,
    aluno_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    status status_submissao_enum NOT NULL DEFAULT 'EM_ANDAMENTO',
    tempo_gasto_segundos INTEGER NOT NULL DEFAULT 0,
    data_inicio TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_submissao TIMESTAMPTZ,
    -- Avaliação do Professor
    professor_corretor_id BIGINT REFERENCES usuarios(id),
    nota NUMERIC(4,2), -- Escala 0.00 a 10.00
    parecer_docente TEXT,
    data_avaliacao TIMESTAMPTZ,
    CONSTRAINT uq_submissao_aluno_atividade UNIQUE (atividade_id, aluno_id)
);

-- -----------------------------------------------------------------------------
-- 8. ARTEFATOS PEDAGÓGICOS DA RESOLUÇÃO (IHI GTT, ISHIKAWA, 5W3H, PDCA)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS submissao_gatilhos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submissao_id BIGINT NOT NULL REFERENCES submissoes_atividades(id) ON DELETE CASCADE,
    gatilho_id BIGINT NOT NULL REFERENCES gatilhos_gtt(id),
    categoria_ea_id BIGINT REFERENCES categorias_eventos_adversos(id),
    confirmou_dano BOOLEAN NOT NULL DEFAULT FALSE,
    justificativa_dano TEXT,
    dano_presente_admissao BOOLEAN NOT NULL DEFAULT FALSE,
    gravidade gravidade_ncc_merp_enum
);

CREATE TABLE IF NOT EXISTS submissao_ishikawa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submissao_id BIGINT NOT NULL UNIQUE REFERENCES submissoes_atividades(id) ON DELETE CASCADE,
    efeito_principal TEXT NOT NULL,
    metodo TEXT,
    mao_de_obra TEXT,
    material TEXT,
    medida TEXT,
    meio_ambiente TEXT,
    maquina TEXT
);

CREATE TABLE IF NOT EXISTS submissao_planos_5w3h (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submissao_id BIGINT NOT NULL REFERENCES submissoes_atividades(id) ON DELETE CASCADE,
    o_que TEXT NOT NULL,
    por_que TEXT NOT NULL,
    quem VARCHAR(100) NOT NULL,
    onde VARCHAR(100) NOT NULL,
    quando VARCHAR(100) NOT NULL,
    como TEXT NOT NULL,
    quanto_custa NUMERIC(12, 2),
    como_medir VARCHAR(150)
);

CREATE TABLE IF NOT EXISTS submissao_pdca (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submissao_id BIGINT NOT NULL UNIQUE REFERENCES submissoes_atividades(id) ON DELETE CASCADE,
    planejar TEXT NOT NULL,
    fazer TEXT NOT NULL,
    checar TEXT NOT NULL,
    agir TEXT NOT NULL
);

-- -----------------------------------------------------------------------------
-- 9. ÍNDICES DE PERFORMANCE E CHAVES ESTRANGEIRAS
-- -----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_usuarios_ativo ON usuarios(ativo);
CREATE INDEX IF NOT EXISTS idx_usuarios_perfil ON usuarios(perfil);
CREATE INDEX IF NOT EXISTS idx_gatilhos_modulo_id ON gatilhos_gtt(modulo_id);
CREATE INDEX IF NOT EXISTS idx_turmas_professor ON turmas(professor_responsavel_id);
CREATE INDEX IF NOT EXISTS idx_casos_professor ON casos_clinicos(professor_criador_id);
CREATE INDEX IF NOT EXISTS idx_casos_unidade ON casos_clinicos(unidade_hospitalar_id);
CREATE INDEX IF NOT EXISTS idx_atividades_turma ON atividades_educacionais(turma_id);
CREATE INDEX IF NOT EXISTS idx_atividades_caso ON atividades_educacionais(caso_clinico_id);
CREATE INDEX IF NOT EXISTS idx_submissoes_atividade ON submissoes_atividades(atividade_id);
CREATE INDEX IF NOT EXISTS idx_submissoes_aluno ON submissoes_atividades(aluno_id);
CREATE INDEX IF NOT EXISTS idx_submissoes_status ON submissoes_atividades(status);
CREATE INDEX IF NOT EXISTS idx_submissao_gatilhos_sub ON submissao_gatilhos(submissao_id);
