export * from '../../modulos/usuario/modelos/usuario.modelos';
export * from '../../modulos/gtt/modelos/gtt.modelos';
export * from '../../modulos/unidade/modelos/unidade.modelos';
export * from '../../modulos/turma/modelos/turma.modelos';
export * from '../../modulos/cenario/modelos/cenario.modelos';
export * from '../../modulos/auditoria/modelos/auditoria.modelos';
export * from '../../modulos/qualidade/modelos/qualidade.modelos';
export * from '../../modulos/autenticacao/modelos/autenticacao.modelos';
export * from '../../modulos/indicadores/modelos/indicadores.modelos';
