-- =============================================================================
-- SIGEA-GTT: Sistema Integrado de Gestão e Auditoria Clínica - Global Trigger Tool
-- Script DDL Consolidado (PostgreSQL 16+)
-- Migração Canônica Flyway V1
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. TIPOS ENUMERADOS (ENUMS IDEMPOTENTES)
-- -----------------------------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'perfil_usuario_enum') THEN
        CREATE TYPE perfil_usuario_enum AS ENUM (
            'ADMINISTRADOR',
            'PROFESSOR',
            'ALUNO'
        );
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gravidade_ncc_merp_enum') THEN
        CREATE TYPE gravidade_ncc_merp_enum AS ENUM (
            'CATEGORIA_E', -- Dano temporário com necessidade de intervenção
            'CATEGORIA_F', -- Dano temporário com prolongamento de hospitalização
            'CATEGORIA_G', -- Dano permanente
            'CATEGORIA_H', -- Intervenção para suporte de vida (< 1h)
            'CATEGORIA_I'  -- Óbito com cuidado contribuinte
        );
    END IF;
END $$;

-- -----------------------------------------------------------------------------
-- 2. GESTÃO DE ACESSO E AUTENTICAÇÃO
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_completo VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    matricula_sigaa VARCHAR(12) UNIQUE,
    perfil perfil_usuario_enum NOT NULL,
    senha VARCHAR(255) NOT NULL,
    primeiro_acesso BOOLEAN NOT NULL DEFAULT TRUE,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- -----------------------------------------------------------------------------
-- 3. CONFIGURAÇÕES HOSPITALARES E METODOLOGIA IHI-GTT
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS unidades_hospitalares (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    sigla VARCHAR(20) NOT NULL,
    ativa BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS modulos_gtt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(30) UNIQUE NOT NULL,
    nome VARCHAR(100) NOT NULL,
    descricao TEXT,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS gatilhos_gtt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(10) NOT NULL UNIQUE,
    modulo_id BIGINT NOT NULL REFERENCES modulos_gtt(id) ON DELETE CASCADE,
    descricao TEXT NOT NULL,
    limiar_referencia VARCHAR(150),
    ativo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS categorias_eventos_adversos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE,
    definicao_operacional TEXT NOT NULL,
    ativa BOOLEAN NOT NULL DEFAULT TRUE
);

-- -----------------------------------------------------------------------------
-- 4. AMBIENTE ACADÊMICO, TURMAS E PRONTUÁRIOS SIMULADOS
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS turmas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    professor_responsavel_id BIGINT NOT NULL REFERENCES usuarios(id),
    codigo_disciplina VARCHAR(30) NOT NULL,
    periodo_letivo VARCHAR(20) NOT NULL,
    ano_semestre VARCHAR(10) NOT NULL,
    ativa BOOLEAN NOT NULL DEFAULT TRUE,
    criada_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS turma_alunos (
    turma_id BIGINT NOT NULL REFERENCES turmas(id) ON DELETE CASCADE,
    aluno_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    matriculado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (turma_id, aluno_id)
);

CREATE TABLE IF NOT EXISTS cenarios_clinicos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    professor_criador_id BIGINT NOT NULL REFERENCES usuarios(id),
    titulo VARCHAR(150) NOT NULL,
    descricao_pedagogica TEXT NOT NULL,
    objetivos_aprendizagem TEXT NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS prontuarios_simulados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cenario_id BIGINT NOT NULL REFERENCES cenarios_clinicos(id) ON DELETE CASCADE,
    unidade_hospitalar_id BIGINT NOT NULL REFERENCES unidades_hospitalares(id),
    numero_atendimento VARCHAR(50) NOT NULL,
    idade_paciente INTEGER NOT NULL,
    data_admissao DATE NOT NULL,
    data_alta DATE NOT NULL,
    tempo_permanencia_dias INTEGER NOT NULL,
    sumario_alta TEXT NOT NULL,
    prescricoes_medicas TEXT NOT NULL,
    exames_laboratoriais TEXT NOT NULL,
    relatorio_cirurgico TEXT,
    evolucoes_multiprofissionais TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS atividades_auditoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    turma_id BIGINT NOT NULL REFERENCES turmas(id),
    cenario_id BIGINT NOT NULL REFERENCES cenarios_clinicos(id),
    titulo VARCHAR(150) NOT NULL,
    data_inicio TIMESTAMPTZ NOT NULL,
    data_fim TIMESTAMPTZ NOT NULL,
    tempo_limite_minutos INTEGER NOT NULL DEFAULT 20,
    finalizada BOOLEAN NOT NULL DEFAULT FALSE
);

-- -----------------------------------------------------------------------------
-- 5. REVISÃO RETROSPECTIVA INDIVIDUAL E HOMOLOGAÇÃO DOCENTE
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS revisoes_individuais (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    atividade_id BIGINT NOT NULL REFERENCES atividades_auditoria(id) ON DELETE CASCADE,
    aluno_id BIGINT NOT NULL REFERENCES usuarios(id),
    prontuario_id BIGINT NOT NULL REFERENCES prontuarios_simulados(id),
    tempo_gasto_segundos INTEGER NOT NULL DEFAULT 0,
    finalizada BOOLEAN NOT NULL DEFAULT FALSE,
    data_submissao TIMESTAMPTZ,
    CONSTRAINT uq_revisao_individual UNIQUE (atividade_id, aluno_id, prontuario_id)
);

CREATE TABLE IF NOT EXISTS achados_gatilhos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revisao_individual_id BIGINT NOT NULL REFERENCES revisoes_individuais(id) ON DELETE CASCADE,
    gatilho_id BIGINT NOT NULL REFERENCES gatilhos_gtt(id),
    categoria_ea_id BIGINT REFERENCES categorias_eventos_adversos(id),
    confirmou_dano BOOLEAN NOT NULL DEFAULT FALSE,
    justificativa_dano TEXT,
    dano_presente_admissao BOOLEAN NOT NULL DEFAULT FALSE,
    gravidade gravidade_ncc_merp_enum
);

CREATE TABLE IF NOT EXISTS validacoes_docentes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revisao_individual_id BIGINT NOT NULL UNIQUE REFERENCES revisoes_individuais(id) ON DELETE CASCADE,
    professor_validador_id BIGINT NOT NULL REFERENCES usuarios(id),
    parecer_formativo TEXT NOT NULL,
    homologado BOOLEAN NOT NULL DEFAULT FALSE,
    data_validacao TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- -----------------------------------------------------------------------------
-- 6. FERRAMENTAS DE MELHORIA DA QUALIDADE (ISHIKAWA, 5W3H E PDCA)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS analises_ishikawa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revisao_individual_id BIGINT NOT NULL UNIQUE REFERENCES revisoes_individuais(id) ON DELETE CASCADE,
    efeito_principal TEXT NOT NULL,
    metodo TEXT,
    mao_de_obra TEXT,
    material TEXT,
    medida TEXT,
    meio_ambiente TEXT,
    maquina TEXT
);

CREATE TABLE IF NOT EXISTS planos_acao_5w3h (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revisao_individual_id BIGINT NOT NULL UNIQUE REFERENCES revisoes_individuais(id) ON DELETE CASCADE,
    o_que TEXT NOT NULL,
    por_que TEXT NOT NULL,
    quem VARCHAR(100) NOT NULL,
    onde VARCHAR(100) NOT NULL,
    quando VARCHAR(100) NOT NULL,
    como TEXT NOT NULL,
    quanto_custa NUMERIC(12, 2),
    como_medir VARCHAR(150)
);

CREATE TABLE IF NOT EXISTS ciclos_pdca (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revisao_individual_id BIGINT NOT NULL UNIQUE REFERENCES revisoes_individuais(id) ON DELETE CASCADE,
    planejar TEXT NOT NULL,
    fazer TEXT NOT NULL,
    checar TEXT NOT NULL,
    agir TEXT NOT NULL
);

-- -----------------------------------------------------------------------------
-- 7. ÍNDICES DE PERFORMANCE E CHAVES ESTRANGEIRAS
-- -----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_usuarios_ativo ON usuarios(ativo);
CREATE INDEX IF NOT EXISTS idx_usuarios_perfil ON usuarios(perfil);
CREATE INDEX IF NOT EXISTS idx_gatilhos_modulo_id ON gatilhos_gtt(modulo_id);
CREATE INDEX IF NOT EXISTS idx_turmas_professor ON turmas(professor_responsavel_id);
CREATE INDEX IF NOT EXISTS idx_turmas_ativa ON turmas(ativa);
CREATE INDEX IF NOT EXISTS idx_turma_alunos_aluno ON turma_alunos(aluno_id);
CREATE INDEX IF NOT EXISTS idx_cenarios_professor ON cenarios_clinicos(professor_criador_id);
CREATE INDEX IF NOT EXISTS idx_prontuarios_cenario ON prontuarios_simulados(cenario_id);
CREATE INDEX IF NOT EXISTS idx_prontuarios_unidade ON prontuarios_simulados(unidade_hospitalar_id);
CREATE INDEX IF NOT EXISTS idx_atividades_turma ON atividades_auditoria(turma_id);
CREATE INDEX IF NOT EXISTS idx_atividades_cenario ON atividades_auditoria(cenario_id);
CREATE INDEX IF NOT EXISTS idx_revisoes_atividade ON revisoes_individuais(atividade_id);
CREATE INDEX IF NOT EXISTS idx_revisoes_aluno ON revisoes_individuais(aluno_id);
CREATE INDEX IF NOT EXISTS idx_revisoes_prontuario ON revisoes_individuais(prontuario_id);
CREATE INDEX IF NOT EXISTS idx_achados_revisao ON achados_gatilhos(revisao_individual_id);
CREATE INDEX IF NOT EXISTS idx_achados_gatilho ON achados_gatilhos(gatilho_id);
CREATE INDEX IF NOT EXISTS idx_achados_categoria ON achados_gatilhos(categoria_ea_id);
CREATE INDEX IF NOT EXISTS idx_validacoes_professor ON validacoes_docentes(professor_validador_id);
CREATE INDEX IF NOT EXISTS idx_planos_5w3h_revisao_individual ON planos_acao_5w3h(revisao_individual_id);
